### ISSUE TITLE
destination file not created

### ISSUE THREAD

**Issue by saravanakumard** [nanjingboy/grunt-css-url-replace#6]
The code is as below...

```
css_url_replace:
  options:
    staticRoot: "public"
    replaceBackslashes: true
  files:
    "dest/build.css": [
      "css/custom/test.css"
    ]
```

On executing this task in grunt the dest/build.css is not created.

Please help.
